<a href="https://colab.research.google.com/github/Keshabbu/Datascience/blob/main/Data_Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Data Encoding --> Process of converting non-numeric data to numeric data

OneHotEncoding Encoding

In [ ]:
import pandas as pd

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
df = pd.DataFrame({
    'color' : ['red','blue','green','green','red','blue']
})

In [ ]:
df

   color
0    red
1   blue
2  green
3  green
4    red
5   blue

In [ ]:
# Creating the instance of one hot encoder
encoder = OneHotEncoder()

In [ ]:
# fit the encoder to dataframe and transform the categorical variable
encoded = encoder.fit_transform(df[['color']])

In [ ]:
encoded

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 6 stored elements and shape (6, 3)>

In [ ]:
import pandas as pd
encoded_df = pd.DataFrame(encoded.toarray(),columns=encoder.get_feature_names_out())

In [ ]:
df

   color
0    red
1   blue
2  green
3  green
4    red
5   blue

In [ ]:
encoded_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [ ]:
pd.concat([df, encoded_df], axis = 1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5   blue         1.0          0.0        0.0

In [ ]:
import seaborn as sns
df = sns.load_dataset('tips')

In [ ]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
encoded = encoder.fit_transform(df[['sex','smoker']])

In [ ]:
encoded

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 488 stored elements and shape (244, 4)>

In [ ]:
import pandas as pd
encoded_df = pd.DataFrame(encoded.toarray(),columns=encoder.get_feature_names_out())

In [ ]:
encoded_df

     sex_Female  sex_Male  smoker_No  smoker_Yes
0           1.0       0.0        1.0         0.0
1           0.0       1.0        1.0         0.0
2           0.0       1.0        1.0         0.0
3           0.0       1.0        1.0         0.0
4           1.0       0.0        1.0         0.0
..          ...       ...        ...         ...
239         0.0       1.0        1.0         0.0
240         1.0       0.0        0.0         1.0
241         0.0       1.0        0.0         1.0
242         0.0       1.0        1.0         0.0
243         1.0       0.0        1.0         0.0

[244 rows x 4 columns]

Label Encoder

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.DataFrame({
    'color' : ['red','blue','green','green','red','blue']
})

In [ ]:
df

   color
0    red
1   blue
2  green
3  green
4    red
5   blue

In [ ]:
encoder = LabelEncoder()

In [ ]:
encoder.fit_transform(df['color'])

array([2, 0, 1, 1, 2, 0])

In [ ]:
df

     size
0   small
1  medium
2   large
3  medium
4   small
5   large

Ordinal Encoder

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
df

     size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [ ]:
encoder = OrdinalEncoder(categories=[['small','medium','large']])

In [ ]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

Target Guided Ordinal Encoding

In [ ]:
df = pd.DataFrame({
    'city' : ['New York','London','Paris','Tokyo','New York','Paris'],
    'price' : [200,150,300,250,150,300]
 })

In [ ]:
df

       city  price
0  New York    200
1    London    150
2     Paris    300
3     Tokyo    250
4  New York    150
5     Paris    300

In [ ]:
mean_price = df.groupby('city')['price'].mean().to_dict()

In [ ]:
mean_price

{'London': 150.0, 'New York': 175.0, 'Paris': 300.0, 'Tokyo': 250.0}

In [ ]:
df['city_encoded'] = df['city'].map(mean_price)

In [ ]:
df

       city  price  city_encoded
0  New York    200         175.0
1    London    150         150.0
2     Paris    300         300.0
3     Tokyo    250         250.0
4  New York    150         175.0
5     Paris    300         300.0